### PR TITLE
[ci] add code analysis parallel split job

### PR DESCRIPTION
**Pull request by TomasVotruba**
At first, the CI should fail. But after merge of https://github.com/ScrumWorks/openapi-schema/pull/29 the coding standard is fixed :heavy_check_mark:

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to review and merge :+1:

**Review by AdamLutka — APPROVED** [review]

**Review by AdamLutka — CHANGES_REQUESTED** [review]
Vypada to, ze ted se nektere checky delaji duplicitne, protoze zustaly v puvodnim predpisu buildu, ne?

**Comment by TomasVotruba** [comment]
Mrknu

**Review by AdamLutka — APPROVED** [review]

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
